---
spring:
  datasource:
    url: jdbc:postgresql://localhost/dg-bucket-db-prod
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      springframework:
        cloud:
          task: DEBUG