---

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        input:
          destination: omar-job-manager

logging:
  level:
    org:
      springframework:
        cloud:
          task: DEBUG
          stream: DEBUG